# Generated by Django 5.0.4 on 2024-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='pending', help_text='can be pending, completed, cancelled', max_length=20),
        ),
    ]
